name: Multi Step Workflow

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Step 1 - Print message
        run: echo "Step 1 running"

      - name: Step 2 - Show date
        run: date

      - name: Step 3 - List files
        run: ls -la

      - name: Step 4 - Final message
        run: echo "Workflow completed successfully!"
